import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Mazin Tagelsir
 *
 */
public final class RSSReader {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSReader() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        //used getchild method to get title tag
        int indexOfTitle = getChildElement(channel, "title");

        //default value
        String title = "No Title";

        //if there is a title tag
        if (channel.child(indexOfTitle).numberOfChildren() != 0) {
            title = channel.child(indexOfTitle).child(0).label();
        }

        // no need to check this because link is required child of channel tag
        int indexOfLink = getChildElement(channel, "link");
        String link = channel.child(indexOfLink).child(0).label();

        //gets index of description
        int indexOfDescription = getChildElement(channel, "description");

        //sets description to nothing
        String description = "No description";

        //if there is a desc. - sets description to description tag
        if (channel.child(indexOfDescription).numberOfChildren() != 0) {
            description = channel.child(indexOfDescription).child(0).label();
        }

//        // no need to check this because link is required child of channel tag
//        int indexOfLink = getChildElement(channel, "link");
//        String link = channel.child(indexOfLink).child(0).label();

        //prints title tag in the html doc
        out.println("<html> <head> <title>" + title + "</title>");
        out.println("</head> <body>");

        //for the link in the html on the title
        out.println("<h1> <a href = \"" + link + "\">" + title + "</a></h1>");

        //prints the description as a p tag
        out.println("<p>");
        out.println(description);
        out.println("</p>");

        out.println("<table border=\"1\">");

        //print out the date,source,and news at top of table
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");

    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body>");
        out.println("</html>");

    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        //node can't be less than zero (edge)
        int node = -1;

        for (int i = 0; i < xml.numberOfChildren(); i++) {
            if (xml.child(i).isTag()) {

                //if the child is equal to the name of the desired tag
                if (xml.child(i).label().equals(tag)) {

                    //node will be equal to the child index
                    node = i;
                }
            }
        }
        return node;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
                + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        String sourceURL = ""; //empty to start
        int indexOfpubDate = getChildElement(item, "pubDate");
        int indexOfSource = getChildElement(item, "source");
        int indexOfTitle = getChildElement(item, "title");

        //default pub date
        String pubDate = "No Date Available";

        //if there is a child for the index
        if (indexOfpubDate != -1
                && item.child(indexOfpubDate).numberOfChildren() != 0) {

            //the publication date is the label of that index tag
            pubDate = item.child(indexOfpubDate).child(0).label();
        }

        //default string until made
        String sourceText = "No source available";

        if (indexOfSource != -1
                && item.child(indexOfSource).numberOfChildren() != 0) {

            //declares url to the attribute of the source tag(the url)
            sourceURL = item.child(indexOfSource).attributeValue("url");

            ////declares the text to the label of the source tag
            sourceText = item.child(indexOfSource).child(0).label();

        }

        int linkIndex = getChildElement(item, "link");
        String link = item.child(linkIndex).child(0).label();

        //default title string text
        String title = "No Title available";
        if (indexOfTitle != -1
                && item.child(indexOfTitle).numberOfChildren() != 0) {

            title = item.child(indexOfTitle).child(0).label();
        }

        //html doc output:
        out.println("<tr>");
        out.println("<td>" + pubDate + "</td>"); // date cell
        out.println("<td>" + "<a href = \"" + sourceURL + "\">" + sourceText
                + "</a></td>"); // link cell
        out.println("<td><a href = \"" + link + "\">" + title + "</a></td>");

        out.println("</tr>");

    }

    /**
     * Extra method that checks if rss url is valid. (less space)
     *
     * @param tree
     *            the tree
     * @return valid
     *
     *
     */
    private static boolean isValid(XMLTree tree) {
        boolean valid = false; //declare boolean

        //if there is a tag and it has "rss", & "version"
        if (tree.isTag() && tree.label().equals("rss")
                && tree.hasAttribute("version")) {

            //if version is 2.0
            if (tree.attributeValue("version").equals("2.0")) {
                valid = true; //convert the boolean
            }
        }

        return valid; //return the value
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        out.print("Enter the URL of an RSS 2.0 news feed: ");
        String url = in.nextLine();

        XMLTree tree = new XMLTree1(url); //input rss url

        //calls method in loop to see if RSS feed has valid components
        //if not valid then loops back
        while (!isValid(tree)) {
            out.println("Invalid RSS feed. Please try again:");
            url = in.nextLine();
            tree = new XMLTree1(url);
        }

        XMLTree channel = tree.child(0);

        //asking the user for html name
        out.println("Enter a name for the file you want the HTML to print to");
        String fileName = in.nextLine(); //string that contains input

        //this loop makes sure that the file is html
        while (!fileName.endsWith(".html")) { // makes sure html extension is present
            out.print("file name must end with .html extension. Try again");
            fileName = in.nextLine();
        }

        //converts the string to the desired html document
        SimpleWriter fileOut = new SimpleWriter1L(fileName);

        //outputs the header for the html file in the method
        outputHeader(channel, fileOut);

        /*
         * following loop gets the item tag, even if there is more/less than one
         * sends the tag to the process item method that outputs the file to the
         * html
         */
        for (int i = 0; i < channel.numberOfChildren(); i++) {
            if (channel.child(i).isTag()) {
                if (channel.child(i).label().equals("item")) {
                    XMLTree item = channel.child(i);
                    processItem(item, fileOut);
                }
            }
        }
        outputFooter(fileOut); //outputs the footer to the html doc

        in.close();
        out.close();
        fileOut.close();
    }

}
